const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    description: "Noise-cancelling over-ear headphones.",
    price: 1200,
    image: "/images/p1.jpg",
  },
  {
    id: 2,
    name: "Smart Watch",
    category: "Wearables",
    description: "Track your health and stay connected.",
    price: 150.00,
    image: "/images/p2.png",
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    category: "Electronics",
    description: "Portable speaker with deep bass and waterproof design.",
    price: 699,
    image: "/images/p3.jpg",
  },
  {
    id: 4,
    name: "Gaming Mouse",
    category: "Accessories",
    description: "Ergonomic mouse with customizable RGB lighting.",
    price: 599,
    image: "/images/p4.jpg",
  },
  {
    id: 5,
    name: "Mechanical Keyboard",
    category: "Accessories",
    description: "Backlit mechanical keyboard with blue switches.",
    price: 1500,
    image: "/images/p5.jpg",
  },
  {
    id: 6,
    name: "4K Monitor",
    category: "Electronics",
    description: "Ultra HD monitor with HDR support and thin bezels.",
    price: 3000,
    image: "/images/p6.jpg",
  },
  {
    id: 7,
    name: "Fitness Tracker",
    category: "Wearables",
    description: "Lightweight tracker with heart rate and sleep monitoring.",
    price: 300,
    image: "/images/p7.jpg",
  },
  {
    id: 8,
    name: "Laptop Backpack",
    category: "Bags",
    description: "Water-resistant backpack with multiple compartments.",
    price: 300,
    image: "/images/p8.jpg",
  },
  {
    id: 9,
    name: "Wireless Charger",
    category: "Accessories",
    description: "Fast charging pad compatible with all Qi-enabled devices.",
    price: 400,
    image: "/images/p9.jpg",
  },
  {
    id: 10,
    name: "Drone Camera",
    category: "Gadgets",
    description: "Compact drone with 4K camera and GPS tracking.",
    price: 2500,
    image: "/images/p10.jpg",
  },
];

export default products;
